services:

  ph-eye-en:
    image: philterd/ph-eye:1.2.1
    container_name: philter-ph-eye-en-1
    ports:
      - "5000"
    networks:
      - philter

  philter:
    image: philterd/philter:3.3.0
    ports:
      - "8080:8080"
    volumes:
      - ./philter.properties:/opt/philter/philter.properties
      - ./policies/:/opt/philter/policies/
    networks:
      - philter

networks:
  philter: